### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by ProgramminCat** [temporary-containers-firefox/temporary-containers#1]
We need a different name than "Temporary Containers" for AMO (addons.mozilla.org), and so people can tell the difference. I was thinking "Temporary Containers Plus", but I'd love to get all of your feedback!

**Comment by ProgramminCat** [comment]
@hondogitsune 

No worries, it’s a great question! We planned to implement a rigorous code review process where all contributions are thoroughly reviewed before being merged. We also will use signed commits to verify the identity of contributors and require two-factor authentication (2FA) for all contributors to protect their accounts.

By using these practices, we aim to maintain a secure and trustworthy codebase. If you have any specific concerns or suggestions, I’d love to hear them!

**Comment by GuilloOme** [comment]
Could be `Disposable Containers`

**Comment by ProgramminCat** [comment]
React with "1" emoji for `Temporary Containers Plus`

React with "2" emoji for `Disposable Containers`

**Comment by ashtonc** [comment]
Temporary Containers Plus helps maintain continuity. Other forks that have chosen similar names to their predecessor:

- μBlock to [uBlock Origin](https://github.com/gorhill/uBlock)
- Hover Zoom to [Hover Zoom+](https://addons.mozilla.org/en-US/firefox/addon/hover-zoom-plus/)
- searX to [SearXNG](https://github.com/searxng/searxng/)
- Paperless to Paperless-ng to [Paperless-ngx](https://github.com/paperless-ngx/paperless-ngx)

**Comment by ProgramminCat** [comment]
## OK, we have a 'winner':
# `Temporary Containers+` / `Temporary Containers Plus`
## `Plus` will be chosen when the `+` character is unavailable

**Comment by Termuellinator** [comment]
I would argue against the "+", if there are places where it can't be named that way. It only risks confusion - like anytime when there are multiple "official" names.

Personally i would like the + better, but as Github doesn't allow that for repo-names, i would suggest sticking to the written out "plus".

**Comment by ProgramminCat** [comment]
Okay, that makes sense.

**Comment by ProgramminCat** [comment]
# `Temporary Containers Plus`
